paths:
  /api/products/producto:
    get:
      summary: Obtener lista de productos
      tags:
        - Products
      responses:
        "200":
          description: Respuesta exitosa, lista de productos
        "500":
          description: Error al obtener productos

  /api/products/{id}:
    get:
      summary: Obtener un producto por ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
      responses:
        "200":
          description: Respuesta exitosa, producto
        "500":
          description: Error al obtener el producto
        "400":
          description: Ingrese un ID válido

  /api/products/:
    post:
      summary: Cargar un producto nuevo
      tags:
        - Products
      responses:
        "200":
          description: Respuesta exitosa, producto creado
        "404":
          description: Titulo y precio son datos obligatorios

  /api/products/{id}:
    put: 
      summary: Editar un producto buscado por ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
      responses:
        "200":
          description: Respuesta exitosa, producto editado
        "404":
          description: No se encontro un producto con ese ID
        "500":
          description: Error al obtener el producto

  /api/products/{id}:
    delete: 
      summary: Eliminar un producto buscado por ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
      responses:
        "200":
          description: Respuesta exitosa, producto eliminado
        "404":
          description: No se encontro un producto con ese ID
        "500":
          description: Error al obtener el producto